[package]
name = "advance_lab"
version = "0.1.0"
edition = "2021"

[dependencies]
criterion = "0.4"
rand = "0.8.5"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "radix_sort"
harness = false
